trigger: none

variables:
- template: eng/common-variables.yml
- name: EnableRichCodeNavigation
  value: true

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      enableMicrobuild: true
      enablePublishUsingPipelines: false
      useBuildManifest: ${{ variables['_UseBuildManifest'] }}
      workspace:
        clean: all
      jobs:
      - job: Windows_NT
        timeoutInMinutes: 90
        enableRichCodeNavigation: true
        pool:
          ${{ if eq(variables._RunAsPublic, True) }}:
            name: NetCorePublic-Pool
            queue: BuildPool.Server.Amd64.VS2017.Arcade.Open
          ${{ if eq(variables._RunAsInternal, True) }}:
            name: NetCoreInternal-Pool
            queue: BuildPool.Server.Amd64.VS2017.Arcade
        strategy:
          matrix:
            Build_Release:
              _BuildConfig: Release
              _SignType: test
        preSteps:
        - checkout: self
          clean: true
        steps:
        - script: eng\common\cibuild.cmd
            -configuration $(_BuildConfig)
            -prepareMachine
            $(_InternalBuildArgs)
            /p:Test=false
          displayName: Windows Build